version: '3.3'
services:
  stripcontrol:
    image: pthum/stripcontrol:0.0.1-SNAPSHOT
    privileged: true
    ports:
      - '8080:8080'
    expose:
      - '8080'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    volumes:
      - "/home/pi/scdocker:/stripcontrol/config"
