#spring.datasource.url=jdbc:postgresql://localhost:5432/stripcontrol
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring:
  devtools:
    add-properties: false
debug: false